USE QLDA 
GO
--lab1.cau3.1--
SELECT * FROM NHANVIEN WHERE PHG = 4;

--lab1.cau3.2--
SELECT * FROM NHANVIEN WHERE dbo.NHANVIEN.LUONG > 30000;

--lab1.cau3.3--
SELECT * FROM NHANVIEN WHERE ( LUONG > 25000 AND PHG = 4 ) OR ( LUONG > 30000 AND PHG = 5 );

--lab1.cau3.4--
SELECT MANV, CONCAT(HONV,' ', TENLOT ,' ', TENNV) AS HOVATEN FROM NHANVIEN WHERE DCHI LIKE N'%TP HCM%';

--lab1.cau3.5--
SELECT MANV, CONCAT(HONV,' ', TENLOT ,' ', TENNV) AS HOVATEN FROM NHANVIEN WHERE HONV LIKE 'N%';

--lab1.cau3.6--
SELECT MANV, CONCAT(HONV,' ', TENLOT ,' ', TENNV) AS HOVATEN, NGSINH,DCHI FROM NHANVIEN WHERE HONV= N'Đinh' AND TENLOT = N'Bá' AND TENNV = N'Tiên';
