
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ASMGD2;


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

public class QLNV extends javax.swing.JFrame {

    /**
     * Creates new form QLNV
     */
    
    List<NhanVien> ds = new ArrayList<>();
    String remanv = "\\d+";
    String retuoi = "\\d+";
    String reluong = "\\d+\\.{0,1}\\d{0,1}";
    String remail = "\\D\\w+@\\D\\w+\\.\\D\\w+";
    String[] header = {"Code Staff", "Fullname", "Age", "Email", "Salary"};
    DefaultTableModel model;
    JTextArea talot;
Date tg ,tg2;
    public QLNV() {
        initComponents();
        table();
//        getNhanVien();
        addRow();
        uprecord(-1);
        ngay();
    tg = new Date();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lmanv = new javax.swing.JLabel();
        lhoten = new javax.swing.JLabel();
        ltuoi = new javax.swing.JLabel();
        lmail = new javax.swing.JLabel();
        lluong = new javax.swing.JLabel();
        txthonv = new javax.swing.JTextField();
        txtmanv = new javax.swing.JTextField();
        txttuoi = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        txtluong = new javax.swing.JTextField();
        btnpre1 = new javax.swing.JButton();
        btnpre2 = new javax.swing.JButton();
        btnnext2 = new javax.swing.JButton();
        btnnext1 = new javax.swing.JButton();
        txtrecord = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnnew = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnfind = new javax.swing.JButton();
        btnopen = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        txtngay = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ NHÂN VIÊN");
        setLocation(new java.awt.Point(100, 100));
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(191, 255, 185), new java.awt.Color(255, 212, 144), new java.awt.Color(179, 255, 120), new java.awt.Color(160, 191, 255)));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setToolTipText("");
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        lmanv.setForeground(new java.awt.Color(255, 255, 255));
        lmanv.setText("CODE STAFF");

        lhoten.setForeground(new java.awt.Color(255, 255, 255));
        lhoten.setText("FULLNAME");

        ltuoi.setForeground(new java.awt.Color(255, 255, 255));
        ltuoi.setText("AGE");

        lmail.setForeground(new java.awt.Color(255, 255, 255));
        lmail.setText("EMAIL");

        lluong.setForeground(new java.awt.Color(255, 255, 255));
        lluong.setText("SALARY");

        txthonv.setBackground(new java.awt.Color(51, 51, 51));
        txthonv.setForeground(new java.awt.Color(255, 255, 255));
        txthonv.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 226, 224), new java.awt.Color(194, 255, 222)));
        txthonv.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txthonv.setSelectionColor(new java.awt.Color(255, 255, 255));

        txtmanv.setBackground(new java.awt.Color(51, 51, 51));
        txtmanv.setColumns(1);
        txtmanv.setForeground(new java.awt.Color(255, 255, 255));
        txtmanv.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(201, 207, 255), new java.awt.Color(255, 219, 225)));
        txtmanv.setCaretColor(new java.awt.Color(0, 0, 0));
        txtmanv.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtmanv.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtmanv.setSelectionColor(new java.awt.Color(255, 255, 255));

        txttuoi.setBackground(new java.awt.Color(51, 51, 51));
        txttuoi.setForeground(new java.awt.Color(255, 255, 255));
        txttuoi.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(190, 213, 255), new java.awt.Color(153, 255, 178)));
        txttuoi.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txttuoi.setSelectionColor(new java.awt.Color(255, 255, 255));

        txtmail.setBackground(new java.awt.Color(51, 51, 51));
        txtmail.setForeground(new java.awt.Color(255, 255, 255));
        txtmail.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 197, 125), new java.awt.Color(162, 170, 255)));
        txtmail.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtmail.setSelectionColor(new java.awt.Color(255, 255, 255));

        txtluong.setBackground(new java.awt.Color(51, 51, 51));
        txtluong.setForeground(new java.awt.Color(255, 255, 255));
        txtluong.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(138, 255, 163), new java.awt.Color(144, 172, 255)));
        txtluong.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtluong.setSelectionColor(new java.awt.Color(255, 255, 255));

        btnpre1.setBackground(new java.awt.Color(51, 51, 51));
        btnpre1.setForeground(new java.awt.Color(255, 255, 255));
        btnpre1.setText("|<");
        btnpre1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(182, 243, 255), new java.awt.Color(138, 157, 255)));
        btnpre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpre1ActionPerformed(evt);
            }
        });

        btnpre2.setBackground(new java.awt.Color(51, 51, 51));
        btnpre2.setForeground(new java.awt.Color(255, 255, 255));
        btnpre2.setText("<<");
        btnpre2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(162, 222, 255), new java.awt.Color(145, 144, 255)));
        btnpre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpre2ActionPerformed(evt);
            }
        });

        btnnext2.setBackground(new java.awt.Color(51, 51, 51));
        btnnext2.setForeground(new java.awt.Color(255, 255, 255));
        btnnext2.setText(">>");
        btnnext2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(201, 229, 255), new java.awt.Color(165, 188, 255)));
        btnnext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnext2ActionPerformed(evt);
            }
        });

        btnnext1.setBackground(new java.awt.Color(51, 51, 51));
        btnnext1.setForeground(new java.awt.Color(255, 255, 255));
        btnnext1.setText(">|");
        btnnext1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(184, 224, 255), new java.awt.Color(160, 168, 255)));
        btnnext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnext1ActionPerformed(evt);
            }
        });

        txtrecord.setForeground(new java.awt.Color(255, 255, 255));
        txtrecord.setText("Record:  1 of 10");

        jtable.setBackground(new java.awt.Color(0, 0, 0));
        jtable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(241, 200, 255), new java.awt.Color(194, 225, 255), new java.awt.Color(234, 222, 215), new java.awt.Color(174, 236, 217)));
        jtable.setForeground(new java.awt.Color(255, 255, 255));
        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Code Staff", "Fullname", "Age", "Email", "Salary"
            }
        ));
        jtable.setGridColor(new java.awt.Color(142, 193, 218));
        jtable.setSelectionBackground(new java.awt.Color(109, 154, 219));
        jtable.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(187, 219, 217), new java.awt.Color(184, 210, 255)));

        btnnew.setBackground(new java.awt.Color(102, 102, 102));
        btnnew.setText("New");
        btnnew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(102, 102, 102));
        btnsave.setText("Save");
        btnsave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(102, 102, 102));
        btndelete.setText("Delete");
        btndelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnfind.setBackground(new java.awt.Color(102, 102, 102));
        btnfind.setText("Find");
        btnfind.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });

        btnopen.setBackground(new java.awt.Color(102, 102, 102));
        btnopen.setText("Open");
        btnopen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopenActionPerformed(evt);
            }
        });

        btnexit.setBackground(new java.awt.Color(102, 102, 102));
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnfind, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnopen, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnopen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnfind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnnew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnexit)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        txtngay.setBackground(new java.awt.Color(204, 204, 204));
        txtngay.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtngay.setForeground(new java.awt.Color(255, 255, 255));
        txtngay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtngay.setText("00:00");
        txtngay.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(203, 207, 255), new java.awt.Color(196, 255, 187)));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("VNI-Times", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(191, 255, 207));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STAFF MANAGER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        img.setForeground(new java.awt.Color(255, 255, 255));
        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setText("IMAGE");
        img.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(185, 255, 178), new java.awt.Color(255, 219, 166), new java.awt.Color(169, 213, 114), new java.awt.Color(176, 200, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpre1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lhoten, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ltuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lluong)
                            .addComponent(lmanv))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txthonv)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 214, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lmail, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnpre2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnnext2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnnext1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtrecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(33, 33, 33)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtngay, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtngay, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txthonv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lhoten, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ltuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lluong, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrecord)
                    .addComponent(btnnext1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnext2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpre2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpre1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        writefile();
        tg2 = new Date();
        long a = tg.getTime();
        long b = tg2.getTime();
        long t = b-a;
        JOptionPane.showMessageDialog(this, t);
        this.setVisible(false);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopenActionPerformed
        try {
            FileReader fr = new FileReader("data.txt");
            BufferedReader br = new BufferedReader(fr);
            String line;
            while ((line = br.readLine()) != null) {
                String[] txt = line.split(",");
                NhanVien nv = new NhanVien(Integer.parseInt(txt[0]), txt[1], Integer.parseInt(txt[2]), txt[3], Double.parseDouble(txt[4]));
                ds.add(nv);
            }
            fr.close();
            br.close();
            addRow();
            writeform(0);
            loadimg(0);
            btnsave.setText("Update");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(QLNV.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(QLNV.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnopen.setEnabled(false);
    }//GEN-LAST:event_btnopenActionPerformed

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
        // TODO add your handling code here:
        int count = 0;
        String manv = JOptionPane.showInputDialog(this, "Enter the employee code you need to find:");
        for (NhanVien tim : ds) {
            if (manv.equalsIgnoreCase(String.valueOf(tim.getManv()))) {
                writeform(ds.indexOf(tim));
                count =0;
                break;
            } else {

                count = 1;
                //
            }
        }
        if (count == 1) {
            JOptionPane.showMessageDialog(this, "Does not exist");
        }
    }//GEN-LAST:event_btnfindActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) jtable.getModel();
        int index = jtable.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "You have not selected the object to delete");
        } else {
            NhanVien nv = ds.get(index);
            try {
                for (NhanVien nv1 : ds) {
                    if (nv1.getManv() == nv.getManv()) {
                        ds.remove(nv1);
                        addRow();
                        JOptionPane.showMessageDialog(rootPane, "Delete Successful");
                    }
                    btnnewActionPerformed(evt);
                }
            } catch (Exception e) {
                System.out.println("Error to delete: " + e);
            }
        }
        writefile();
        uprecord(index);
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) jtable.getModel();
        int index = jtable.getSelectedRow();
        int count = 0;
        if (index >= 0) {
            updateform(index);
        } else {
            saveform();
        }
        addRow();
        uprecord(index);
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
        try {
            model = (DefaultTableModel) jtable.getModel();
            int index = jtable.getSelectedRow();
            txtmanv.setText("");
            txtmanv.setEnabled(true);
            txthonv.setText("");
            txttuoi.setText("");
            txtmail.setText("");
            txtluong.setText("");
            btnsave.setText("Save");
            if (index < 0) {
                index = 0;
                jtable.removeRowSelectionInterval(index, index);
            } else {
                jtable.removeRowSelectionInterval(index, index);
            }
            uprecord(-1);
        } catch (Exception e) {
            System.out.println("Error from new create" + e);
        }
    }//GEN-LAST:event_btnnewActionPerformed

    private void jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMouseClicked
        // TODO add your handling code here:
        btnsave.setText("Update");
        model = (DefaultTableModel) jtable.getModel();
        int index = jtable.getSelectedRow();
        writeform(index);
        uprecord(index);
        loadimg(index);
    }//GEN-LAST:event_jtableMouseClicked

    private void btnnext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnext1ActionPerformed
        // TODO add your handling code here:
        int index = ds.size();
        writeform(index - 1);
        loadimg(index-1);
    }//GEN-LAST:event_btnnext1ActionPerformed

    private void btnnext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnext2ActionPerformed
        model = (DefaultTableModel) jtable.getModel();
        int index = jtable.getSelectedRow();
        for (NhanVien nv : ds) {
            if (!txtmanv.getText().equals("")) {
                //                 System.out.println(nv.getManv());

                if (txtmanv.getText()== nv.getManv()) {
                    index = ds.indexOf(nv);

                    break;
                }
            } else {

                index = -1;
            }
        }
        if (index < ds.size() - 1) {
            writeform(index + 1);
            loadimg(index+1);
            //            System.out.println(index);
            System.out.println(index);
            //                        jtable.setRowSelectionInterval(index+1, index+1);
        } else if (index == ds.size() - 1) {
            JOptionPane.showMessageDialog(this, "Being in the last place");
        }
    }//GEN-LAST:event_btnnext2ActionPerformed

    private void btnpre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpre2ActionPerformed
        // TODO add your handling code here:
        try {
            model = (DefaultTableModel) jtable.getModel();
            int index = jtable.getSelectedRow();
            for (NhanVien nv : ds) {
                if (!txtmanv.getText().equals("")) {
                    if (txtmanv.getText() == nv.getManv()) {
                        index = ds.indexOf(nv);
                    }
                } else {
                    index = 1;
                }
            }
            if (ds.size() > 0) {
                if (index > 0) {
                    writeform(index - 1);
                    loadimg(index-1);
                    //                       jtable.setRowSelectionInterval(index-1, index-1);
                } else if (index <= 0) {
                    JOptionPane.showMessageDialog(this, "Being in first place");
                    jtable.setRowSelectionInterval(index, index);
                }
            }
        } catch (Exception e) {
            System.out.println("Error from previous " + e);
        }
    }//GEN-LAST:event_btnpre2ActionPerformed

    private void btnpre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpre1ActionPerformed
        // TODO add your handling code here:
        int index = 0;
        writeform(index);
        loadimg(index);
    }//GEN-LAST:event_btnpre1ActionPerformed
  public void loadimg(int i){ 
     String pic = Picture.getImgs(i);
//      System.out.println(pic);
        img.setIcon(new ImageIcon(pic));
     
        img.setSize(100,100);
  }
    public void ngay() {
        Thread th1 = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    while (true) {
                        Date time = new Date();
                        SimpleDateFormat fm = new SimpleDateFormat("hh:mm:ss aa");
                        txtngay.setText(String.valueOf(fm.format(time)));
                        Thread.sleep(1000);
                    }

                } catch (Exception e) {
                    System.out.println("Error to datetime : " + e);
                }
            }

        });
        th1.start();
    }    public boolean checkform() {
        if (txtmanv.getText().matches(remanv) && txtluong.getText().matches(reluong) && txttuoi.getText().matches(retuoi) && txtmail.getText().matches(remail)) {
            return true;
        } else {
            return false;
        }
    }
    
    public void saveform() {
        int count = 0;
        try {
            if (!txtmanv.getText().equals("") && !txthonv.getText().equals("") && !txtmail.equals("") && !txtluong.getText().equals("") && !txttuoi.getText().equals("")) {
                if (checkform()) {
                    if (ds.size() == 0) {
                        if (19 <= Integer.parseInt(txttuoi.getText()) && 55 >= Integer.parseInt(txttuoi.getText())) {
                            if (Double.parseDouble(txtluong.getText()) >= 5000000) {
                                NhanVien nv = new NhanVien();
                                nv.setManv(Integer.parseInt(txtmanv.getText()));
                                 nv.setHoten(txthonv.getText());
                                  nv.setTuoi(Integer.parseInt(txttuoi.getText()));
                                    nv.setMail(txtmail.getText());
                                    nv.setLuong(txtluong.getText());
                                ds.add(nv);
                                JOptionPane.showMessageDialog(this, "Successfully added employees");
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "Salary must than be more 5000000");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Age from 19 to 55");
                        }
                    } else {
                        for (NhanVien stt1 : ds) {
                            if (txtmanv.getText().equalsIgnoreCase(String.valueOf(stt1.getManv()))) {
                                JOptionPane.showMessageDialog(this, "Code staff already exists");
                                count = 0;
                                break;
                            } else {
                                count = 1;
                            }
                        }
                        if (count == 1) {

                            if (19 <= Integer.parseInt(txttuoi.getText()) && 55 >= Integer.parseInt(txttuoi.getText())) {
                                NhanVien nv = new NhanVien(Integer.parseInt(txtmanv.getText()), txthonv.getText(), Integer.parseInt(txttuoi.getText()), txtmail.getText(), Double.parseDouble(txtluong.getText()));
                                ds.add(nv);
                                JOptionPane.showMessageDialog(this, "Successfully added employees");
                            } else {
                                JOptionPane.showMessageDialog(this, "Age from 19 to 55");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Add failed employees");
                        }
                    }

                } else {
                    if (!txtmanv.getText().matches(remanv)) {
                        JOptionPane.showMessageDialog(rootPane, "Please enter the Employee Code as a number");
                    }
                    if (!txttuoi.getText().matches(retuoi)) {
                        JOptionPane.showMessageDialog(rootPane, "Please enter Age as a number");
                    }
                    if (!txtluong.getText().matches(reluong)) {
                        JOptionPane.showMessageDialog(rootPane, "Please enter Salary as a number");
                    }
                    if (!txtmail.getText().matches(remail)) {
                        JOptionPane.showMessageDialog(rootPane, "Please enter Email in correct format");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please enter full information");
            }

        } catch (Exception e) {
            System.out.println("Error from save form" + e);
        }
    }

    public void updateform(int index) {
        NhanVien nv1 = ds.get(index);
        int tb = JOptionPane.showConfirmDialog(this, "Are you sure you will update?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (tb == JOptionPane.YES_OPTION) {
            if (!txtmanv.getText().equals("") && !txthonv.getText().equals("") && !txtmail.equals("") && !txtluong.getText().equals("") && !txttuoi.getText().equals("")) {
                if (checkform()) {
                    if (19 <= Integer.parseInt(txttuoi.getText()) && 55 >= Integer.parseInt(txttuoi.getText())) {
                        if (Double.parseDouble(txtluong.getText()) >= 5000000) {

                        for (NhanVien stt : ds) {
                            if (stt.getManv() == nv1.getManv()) {
                                stt.setHoten(txthonv.getText());
                                stt.setTuoi(Integer.parseInt(txttuoi.getText()));
                                stt.setMail(txtmail.getText());
                                stt.setLuong(Double.parseDouble(txtluong.getText()));
                                JOptionPane.showMessageDialog(rootPane, "Update successful");
                            }
                        }
                        }
                        else{ 
                JOptionPane.showMessageDialog(rootPane, "Salary must than be more 5000000");
                                }
                    } else {
                        JOptionPane.showMessageDialog(this, "Age from 19 to 55");
                    }
                } else {
                    if (!txtmanv.getText().matches(remanv)) {
                        JOptionPane.showMessageDialog(rootPane, "Please enter the Employee Code as a number");
                    }
                    if (!txttuoi.getText().matches(retuoi)) {
                        JOptionPane.showMessageDialog(rootPane, "Please enter Age as a number");
                    }
                    if (!txtluong.getText().matches(reluong)) {
                        JOptionPane.showMessageDialog(rootPane, "Please enter Salary as a number");
                    }
                    if (!txtmail.getText().matches(remail)) {
                        JOptionPane.showMessageDialog(rootPane, "Please enter Email in correct format");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please enter full information");
            }
        }
    }        public void writefile() {
        FileWriter fw;
        try {
            fw = new FileWriter("data.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            for (NhanVien item : ds) {
                bw.write(item.getManv() + "," + item.getHoten() + "," + item.getTuoi() + "," + item.getMail() + "," + item.getLuong());
                bw.write("\n");

            }
            bw.flush();
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(QLNV.class.getName()).log(Level.SEVERE, null, ex);
        }

    }    public void table() {
        model = new DefaultTableModel();
        model.addColumn(header);
        model.setColumnIdentifiers(header);
        jtable.setModel(model);
    }

    public void addRow() {
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        for (NhanVien nv : ds) {
            model.addRow(new Object[]{String.valueOf(nv.getManv()), nv.getHoten(), String.valueOf(nv.getTuoi()), nv.getMail(), String.valueOf(nv.getLuong())});
        }
        model.fireTableDataChanged();
    }

    public void writeform(int i) {
        txtmanv.setText(String.valueOf(ds.get(i).getManv()));
        txtmanv.setEnabled(false);
        txthonv.setText((String) ds.get(i).getHoten());
        txttuoi.setText(String.valueOf(ds.get(i).getTuoi()));
        txtmail.setText((String) ds.get(i).getMail());
        txtluong.setText(String.valueOf(ds.get(i).getLuong()));
        jtable.setRowSelectionInterval(i, i);
        uprecord(i);
    }

    public void uprecord(int i) {
        if (jtable.getRowCount() == 0) {
            txtrecord.setText("Record : none row in table");
        } else {
            txtrecord.setText("Record : " + (i + 1) + " of " + ds.size());
        }
    }

//    public void getNhanVien() {
//        ds.add(new NhanVien(1, "Nguyen Thanh Ha", 19, "thanhha@gmail.com", 12345));
//        ds.add(new NhanVien(2, "Nguyen Ngoc Huyen", 19, "huyen@gmail.com", 12346));
//        ds.add(new NhanVien(3, "Pham Thi Cam Vy", 19, "vy@gmail.com", 12423));
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             QLNV qlnv =    new QLNV();
            qlnv.setVisible(true);
            qlnv.setLocation(400, 100);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnfind;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnnext1;
    private javax.swing.JButton btnnext2;
    private javax.swing.JButton btnopen;
    private javax.swing.JButton btnpre1;
    private javax.swing.JButton btnpre2;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable;
    private javax.swing.JLabel lhoten;
    private javax.swing.JLabel lluong;
    private javax.swing.JLabel lmail;
    private javax.swing.JLabel lmanv;
    private javax.swing.JLabel ltuoi;
    private javax.swing.JTextField txthonv;
    private javax.swing.JTextField txtluong;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtmanv;
    public static javax.swing.JLabel txtngay;
    private javax.swing.JLabel txtrecord;
    private javax.swing.JTextField txttuoi;
    // End of variables declaration//GEN-END:variables

//    @Override
//    public void run() {
//        try {
//            Ngay();
//        } catch (InterruptedException ex) {
//            Logger.getLogger(QLNV.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
}
