CREATE database `IT17303_NguyenThanhHa_lab4`;
use IT17303_NguyenThanhHa_lab4;
CREATE TABLE `VanPhong`(
MaVP INT NOT NULL PRIMARY KEY,
DiaDiem VARCHAR(45) NOT NULL
);
CREATE TABLE `NhanVien`(
MaNV INT NOT NULL PRIMARY KEY,
MaVP INT NOT NULL,
TenNV VARCHAR(45) NOT NULL
);
CREATE TABLE `NhanThan`(
MaNT INT NOT NULL PRIMARY KEY ,
MaNV INT NOT NULL,
TenNT VARCHAR(45) NOT NULL,
NgaySinh Date NOT NULL,
Moiquanhe VARCHAR(45) NOT NULL
);
CREATE TABLE `BatDongSan`(
MaBDS INT NOT NULL,
MaCSH INT NOT NULL,
MaVP INT NOT NULL,
DiaChi VARCHAR(45) NOT NULL
);
CREATE TABLE `ChuSoHuu`(
MaCSH INT NOT NULL PRIMARY KEY,
MaBDS INT NOT NULL,
TenCSH VARCHAR(45) NOT NULL,
SDT INT NOT NULL,
DiaChi VARCHAR(45) NOT NULL
);
CREATE TABLE `TruongPhong`(
MaTP INT NOT NULL,
MaVP INT NOT NULL unique,
MaNV INT NOT NULL unique
);

ALTER TABLE NhanVien
ADD CONSTRAINT FK_NhanVien_MaVP FOREIGN KEY (MaVP) REFERENCES VanPhong(MaVP);
ALTER TABLE TruongPhong
ADD CONSTRAINT FK_TruongPhong_MaVP FOREIGN KEY (MaVP) REFERENCES VanPhong(MaVP)  ,
ADD CONSTRAINT FK_TruongPhong_MaNV FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)  ;
ALTER TABLE NhanThan
ADD CONSTRAINT FK_NhanThan_MaNV FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV);
ALTER TABLE BatDongSan
ADD CONSTRAINT FK_BatDongSab_MaVP FOREIGN KEY (MaVP) REFERENCES VanPhong(MaVP),
ADD CONSTRAINT FK_batdongsan_MaCSH FOREIGN KEY (MaCSH) REFERENCES ChuSoHuu(MaCSH);
alter table ChuSoHuu
drop column MaBDS;
alter table NhanVien
ADD column DiaChi varbinary(45) not null;
alter table TruongPhong
add constraint PK_TruongPhong primary key (MaTP);





