CREATE DATABASE COM2034_CA1
GO
USE COM2034_PS2052_CA1
GO
CREATE TABLE LOAIVATTU(
MALOAI INT PRIMARY KEY NOT NULL,
TENLOAI NVARCHAR(100) NOT NULL,
MOTA NVARCHAR(200),
)

CREATE TABLE VATTU(
MAVT INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TENVT NVARCHAR(100) NOT NULL,
DONVUTIH NVARCHAR(50) ,
DONGIA INT ,
MALOAI INT NOT NULL
)

ALTER TABLE VATTU 
ADD CONSTRAINT FK_VT_LVT FOREIGN KEY (MALOAI) REFERENCES LOAIVATTU(MALOAI);

INSERT INTO LOAIVATTU VALUES
(1,N'Cốt liệu cây dựng',N'Các loại cát, sỏi, đá dăm'),
(2,N'Gạch, đá ốp lát',N'Các loại gạch, đá ốp'),
(3,N'Vật liệu xây',N'Các laoij gạch ốp, đá ốp'),
(4,N'Kính xây dựng',N'Các loại kính thường, kính các nhiệt'),
(5,N'Sắ thép',N'Các loại sắt thép');

INSERT INTO VATTU VALUES
(N'Cát tự nhiên',N'Khối',200000,1),
(N'Cát nghiền',N'Khối',250000,1),
(N'Gạch đất sét nung',N'Viên',1000,3),
(N'gạch bê tông',N'Viên',1200,3),
(N'Gạch ống tuyenl lỗ tròn',N'Viên',700,3);

DROP PROC IF EXISTS LOCTHEODONVITINH_PROC ;
GO
CREATE PROC LOCTHEODONVITINH_PROC 
@DONVITINH NVARCHAR(50)
AS
BEGIN
		SELECT MAVT,TENVT,DONVUTIH,DONGIA,TENLOAI,MOTA FROM VATTU V INNER JOIN LOAIVATTU L ON V.MALOAI = L.MALOAI WHERE DONVUTIH = @DONVITINH;
END

EXEC LOCTHEODONVITINH_PROC N'Khối'

DROP function IF EXISTS	  TONGVT_FUNCTION 
GO
CREATE FUNCTION TONGVT_FUNCTION  (@MALOAI INT) 
RETURNS TABLE
AS

RETURN (SELECT V.MALOAI, TENLOAI,COUNT(V.MALOAI) AS TONGVT FROM VATTU V INNER JOIN LOAIVATTU L ON V.MALOAI = L.MALOAI GROUP BY V.MALOAI , TENLOAI HAVING V.MALOAI = @MALOAI);

SELECT * FROM dbo.TONGVT_FUNCTION (3)

DROP TRIGGER IF EXISTS UPDATE_DONGIA_TRIGGER
GO
CREATE TRIGGER UPDATE_DONGIA_TRIGGER ON VATTU FOR UPDATE
AS
BEGIN
		IF(UPDATE(DONGIA))
		begin
		print N'Không cho cập nhật'
		rollback
		end
END

UPDATE VATTU SET DONGIA = 10000 WHERE MALOAI = 1;


DROP VIEW IF EXISTS THONGTINVATTU_VIEW
GO
CREATE VIEW THONGTINVATTU_VIEW
AS
SELECT V.MALOAI,V.TENVT,V.DONVUTIH,V.DONGIA FROM VATTU V INNER JOIN LOAIVATTU L ON V.MALOAI = L.MALOAI AND L.TENLOAI LIKE N'%Vật liệu xây%'


select * from THONGTINVATTU_VIEW
