Create database COM2034_PS20520_THANHHA;
GO
USE COM2034_PS20520_THANHHA 
GO
CREATE TABLE PHONG(
MAPHONG NVARCHAR(9) PRIMARY KEY NOT NULL,
LOAIPHONG NVARCHAR(20) NOT NULL,
SOKHACHTOIDA INT NOT NULL,
GIAPHONG FLOAT NOT NULL,
MOTA NVARCHAR(255) )
 CREATE TABLE DATPHONG(
 MADATPHONG NVARCHAR(9) PRIMARY KEY NOT NULL,
 MAPHONG NVARCHAR(9) NOT NULL,
 MAKH NVARCHAR(20) NOT NULL,
 NGAYDAT DATE ,
 GIOBATDAU TIME,
 GIOKETTHUC TIME,
 TIENDATCOC FLOAT,
 GHICHU NVARCHAR(200),
 TRANGTHAIDAT NVARCHAR(50)
 )
 ALTER TABLE DATPHONG
 ADD CONSTRAINT FK_PHONG_DATPHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG);

 INSERT INTO PHONG VALUES
 (N'P0001',N'LOAI 1',20,60000,''),
 (N'P0002',N'LOAI 1',25,80000,''),
 (N'P0003',N'LOAI 2',15,50000,''),
 (N'P0004',N'LOAI 3',20,50000,'');

 INSERT INTO DATPHONG VALUES 
 (N'DP0001',N'P0001',N'KH0001','2018-03-26','11:00:00','13:00:00',100,'',N'Đã đặt'),
 (N'DP0002',N'P0002',N'KH0002','2018-03-27','17:15:00','19:15:00',50,'',N'Đã huỷ'),
 (N'DP0003',N'P0003',N'KH0003','2018-03-26','20:30:00','22:15:00',100,'',N'Đã đặt'),
 (N'DP0004',N'P0004',N'KH0004','2018-04-01','19:30:00','21:50:00',200,'',N'Đã đặt');

 --2 THUC HIỆN CÁC YÊU CẦU
 --2.1
 DROP VIEW IF EXISTS THONGTIN_VIEW;
 go
 CREATE VIEW THONGTIN_VIEW
 AS
 SELECT P.MAPHONG,LOAIPHONG,MAKH,TIENDATCOC,TRANGTHAIDAT FROM PHONG P INNER JOIN DATPHONG D ON P.MAPHONG = D.MAPHONG;

 SELECT * FROM THONGTIN_VIEW WHERE TRANGTHAIDAT LIKE N'%Đã đặt%';

 --2.2
 DROP FUNCTION IF EXISTS SOPHUTTHUE_FUNCTION;
 GO
 CREATE FUNCTION  SOPHUTTHUE_FUNCTION (@MADATPHONG NVARCHAR(9))
 RETURNS INT
 AS

 BEGIN
  DECLARE @TONGPHUT INT;
  SET @TONGPHUT = (SELECT DATEDIFF(MI,GIOBATDAU,GIOKETTHUC) AS INT FROM DATPHONG WHERE MADATPHONG = @MADATPHONG);
  RETURN @TONGPHUT ;
 END

 SELECT cast( DBO.SOPHUTTHUE_FUNCTION('DP0001') as nvarchar) + N'  Phút';


 --2.3
 DROP PROC IF EXISTS THONGTINDATPHONG_PROC;
 GO
 CREATE PROC THONGTINDATPHONG_PROC @TUNGAY DATE , @DENNGAY DATE
 AS
 BEGIN
 IF EXISTS ( SELECT * FROM DATPHONG WHERE NGAYDAT BETWEEN @TUNGAY AND @DENNGAY)
 BEGIN
  SELECT LOAIPHONG,GIAPHONG,MADATPHONG,NGAYDAT FROM PHONG P INNER JOIN DATPHONG D ON P.MAPHONG = D.MAPHONG AND NGAYDAT BETWEEN  @TUNGAY AND @DENNGAY;
 END
 ELSE
 PRINT N'Không có thông tin đặt phòng trong khoản thời gian từ ' + cast(@TUNGAY AS NVARCHAR) + N' đến ngày  '+ cast(@DENNGAY AS NVARCHAR);
 END

 EXEC THONGTINDATPHONG_PROC '2018-03-01','2018-03-26';


 --2.4
 DROP TRIGGER IF EXISTS XOAPHONG_TRIGGER
 GO
 CREATE TRIGGER XOAPHONG_TRIGGER ON DATPHONG FOR DELETE
 AS
 BEGIN
 IF  (SELECT TRANGTHAIDAT FROM deleted) LIKE N'%Đã đặt%'
 begin
 print N'Không được xoá phòng có trạng thái đã đặt';
 rollback tran
 end
 END

 delete from DATPHONG WHERE MADATPHONG ='DP0001';