CREATE DATABASE COM2034_PS20520_CA2
GO
USE COM2034_PS20520_CA2
GO
CREATE TABLE PHIEUMUON(
MAPM INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
MASACH VARCHAR(5) NOT NULL,
NGAYMUON DATE,
NGAYTRA DATE)

CREATE TABLE SACH(
MASACH VARCHAR(5) PRIMARY KEY NOT NULL,
TENSACH NVARCHAR(50) NOT NULL,
MATG VARCHAR(5) ,
NHAXB NVARCHAR(50) ,
SOTRANG INT 
)

ALTER TABLE PHIEUMUON
ADD CONSTRAINT FK_PM_SACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH);

INSERT INTO SACH VALUES
('IT001',N'Nhập Môn Lập rình',N'TG001',N'NXB Khoa học-Kỹ thuật',320),
('TN002',N'Ngòi khóc trên cây',N'TG002',N'NXB Trẻ',378),
('KT003',N'60 Giây Vàng Trong Bán Hàng',N'TG003',N'NXB Dân Trí',416),
('IT004',N'Nhập Môn SQL Sever',N'TG001',N'NXB Giáo Dục',400),
('KN005',N'Hài Hước Một Chúc Thế Giới Sẽ Khác Đi',N'TG003',N'NXB Thanh Niên',228);

INSERT INTO PHIEUMUON VALUES
('IT001','2019-10-28','2019-11-12'),
('KT003','2019-11-11','2019-12-22'),
('IT004','2020-02-15','2020-03-02'),
('IT001','2020-03-20','2020-03-30'),
('KT003','2020-05-01','2020-05-15');

--2,3
 DROP VIEW IF EXISTS TONGTIN_VIEW;
 GO
 CREATE VIEW THONGTIN_VIEW 
 AS 
 SELECT * FROM SACH

 SELECT * FROM THONGTIN_VIEW V INNER JOIN PHIEUMUON P ON V.MASACH = P.MASACH AND YEAR(NGAYMUON) = 2020;


 --2.2
 DROP FUNCTION IF EXISTS TONGSOLANMUON_FUNCTION
 GO
 CREATE FUNCTION TONGSOLANMUON_FUNCTION (@MASACH VARCHAR(5))
 RETURNS TABLE
 AS
 RETURN SELECT M.MASACH, TENSACH,MATG,COUNT(M.MASACH)AS N'TONGSOLANMUON' FROM SACH S INNER JOIN PHIEUMUON M ON S.MASACH = M.MASACH GROUP BY M.MASACH,TENSACH,MATG HAVING M.MASACH = @MASACH;
 SELECT * FROM TONGSOLANMUON_FUNCTION('IT001')

 --2.4
  DROP TRIGGER IF EXISTS CHECK_TRIGGER;
  GO 
  CREATE TRIGGER CHECK_TRIGGER ON PHIEUMUON 
  FOR INSERT
  AS
  BEGIN
  IF (SELECT NGAYMUON FROM inserted) >(SELECT NGAYTRA FROM inserted)
  BEGIN
  PRINT N'Ngày trả phải lớn hơn hoặc bằng ngày mượn';
  ROLLBACK TRAN
  END
  END

  INSERT INTO PHIEUMUON 
  VALUES
  ('TN002','2020-11-28','2012-11-12');

  --2.1
  DROP PROC IF EXISTS  BAI2CAU1
  GO
  CREATE PROC BAI2CAU1   @masach VARCHAR(5), @ngaymuon DATE,@ngaytra DATE

	BEGIN

		IF  EXISTS(SELECT * FROM SACH WHERE MaSach = @masach) 
		BEGIN
				PRINT N'THÊM THÀNH CÔNG'
				INSERT INTO PHIEUMUON VALUES (@masach, @ngaymuon,@ngaytra)
			END
			ELSE
			BEGIN
				PRINT N'THÊM THẤT BẠI VÌ KHÔNG TỒN TẠI SACH'
			END
END
	

EXEC BAI2CAU1 'TN006','2020-01-02','2020-01-04';



DROP TRIGGER IF EXISTS THEMSACH_TRIGGER
GO
CREATE TRIGGER THEMSACH_TRIGGER ON SACH INSTEAD OF INSERT 
AS
BEGIN
		IF EXISTS (SELECT MASACH FROM inserted WHERE MASACH IN (SELECT MASACH FROM SACH))  
		BEGIN
				PRINT N'ĐÃ TỒN TẠI MÃ MASACH';
				ROLLBACK TRAN
		END
END
INSERT INTO SACH VALUES
('IT001',N'Nhập Môn Lập rình1',N'TG001',N'NXB Khoa học-Kỹ thuật',320);



DROP PROC IF EXISTS THEMSACH_PROC
GO
CREATE PROC THEMSACH_PROC 
