CREATE DATABASE sinhvien
DROP DATABASE 
go
use sinhvien
GO
CREATE TABLE SINH_VIEN(
MASV INT  PRIMARY KEY NOT NULL,
HOTENSV NVARCHAR(40) ,
NAMSINH INT ,
QUEQUAN NVARCHAR(30))

CREATE TABLE DE_TAI (
MADT CHAR(10) PRIMARY KEY NOT NULL,
TENDT NVARCHAR(30) ,
KINHPHI INT ,
NOITHUCTAP NVARCHAR(30),
MASV INT,
KETQUA DECIMAL(5,2))

INSERT INTO SINH_VIEN VALUES
(1,N'Lê Văn Nam',1990,N'Nghệ An'),
(2,N'Nguyễn Thị Mỹ',1990,N'Thanh Hoá'),
(3,N'Bùi Xuân Đức',1992,N'Hà Nội'),
(4,N'Nguyễn Văn Tùng',NULL,N'Hà Tĩnh'),
(5,N'Lê Khánh Linh',1989,N'Hà Nam');

INSERT INTO DE_TAI VALUES
('Dt01','GIS',100,N'Nghệ An',1,6.80),
('Dt02','ARC GIS',500,N'Nam Định',2,7.65),
('Dt03','Spatial DB',100,N'Hà Tĩnh',2,8.25),
('Dt04','Blockchain',300,N'Nam Định',NULL,NULL),
('Dt05','Cloud Computing',700,N'Nam Định',NULL,NULL);

ALTER TABLE DE_TAI 
ADD CONSTRAINT FK_DT_SV FOREIGN KEY (MASV) REFERENCES SINH_VIEN(MASV) ;

DROP PROC IF EXISTS THONGTIN_DETAI_PROC
GO
CREATE PROC THONGTIN_DETAI_PROC  @KETQUA DECIMAL(5,2)
AS
BEGIN
   SELECT MADT, TENDT,HOTENSV,KINHPHI, NOITHUCTAP,KETQUA FROM DE_TAI D INNER JOIN SINH_VIEN S ON D.MASV = S.MASV AND D.KETQUA > @KETQUA
END

EXEC THONGTIN_DETAI_PROC 7.00


DROP FUNCTION IF EXISTS TONGKINHPHI_FUNTION
GO
CREATE FUNCTION TONGKINHPHI_FUNTION (@MASV INT)
RETURNS TABLE
AS
RETURN SELECT D.MASV,S.HOTENSV,SUM(KINHPHI) AS N'Tổng kinh phí' FROM DE_TAI D INNER JOIN SINH_VIEN S ON D.MASV = S.MASV  GROUP BY D.MASV,S.HOTENSV HAVING D.MASV = @MASV

SELECT * FROM TONGKINHPHI_FUNTION (2)

DROP TRIGGER IF EXISTS XOA_SINHVIEN_TRIGGER
GO
CREATE TRIGGER XOA_SINHVIEN_TRIGGER ON SINH_VIEN INSTEAD OF DELETE
AS
BEGIN
		IF EXISTS(SELECT MASV FROM deleted)
		BEGIN
		   DELETE DE_TAI WHERE MASV IN (SELECT MASV FROM deleted)
		   DELETE SINH_VIEN WHERE MASV IN (SELECT MASV FROM deleted)
		 
		END
END
SELECT * FROM  DE_TAI
DELETE SINH_VIEN WHERE MASV = 1;


DROP VIEW IF EXISTS DEANKHONGTACGIA_VIEW
GO
CREATE VIEW DEANKHONGTACGIA_VIEW
AS
SELECT MASV, TENDT,KINHPHI,NOITHUCTAP,KETQUA FROM DE_TAI 

UPDATE DEANKHONGTACGIA_VIEW SET MASV =5  WHERE MASV IS NULL
SELECT * FROM DEANKHONGTACGIA_VIEW