USE QLXUATKHO_COM1012;
-- Y6.1---
SELECT * FROM HANGHOA order by DONGIA asc;
-- Y6.2---
SELECT HH.MAHH , HH.TENHH, HH.DONVT, HH.DONGIA, LH.MALOAI FROM HANGHOA HH inner JOIN loaihang LH ON HH.LOAI = LH.MALOAI AND LH.TENLOAI LIKE "%Thời trang%";
-- Y6.3---
SELECT LH.MALOAI, LH.TENLOAI ,COUNT(HH.MAHH) AS "TONGSO" FROM  HANGHOA HH INNER JOIN LOAIHANG LH ON HH.LOAI = LH.MALOAI GROUP BY (HH.LOAI)  order by COUNT(HH.MAHH) desc;
-- Y6.4---
SELECT COUNT(CT.SOPHIEU) AS " SỐ PHIẾU", SP.NGAYXUAT, CH.TENCH, CT.MAHH, HH.TENHH, LH.TENLOAI, 
CT.SOLUONG, HH.DONGIA, sum(CT.SOLUONG*HH.DONGIA) AS "Thành tiền" FROM CUAHANG CH INNER JOIN PHIEUXUAT SP ON CH.MACH = SP.MACH 
INNER JOIN ctphieuxuat CT ON SP.SOPHIEU = CT.SOPHIEU INNER JOIN HANGHOA HH ON CT.MAHH = HH.MAHH 
INNER JOIN LOAIHANG LH ON HH.LOAI = LH.MALOAI group by (HH.LOAI);
-- Y6.5---
SELECT month(SP.NGAYXUAT) as 'THÁNG', SUM(CT.SOLUONG*HH.DONGIA) AS "THÀNH TIỀN" FROM PHIEUXUAT SP
INNER JOIN ctphieuxuat CT ON SP.SOPHIEU = CT.SOPHIEU and year(SP.NGAYXUAT) =2021 INNER JOIN HANGHOA HH ON CT.MAHH = HH.MAHH group by(month(SP.NGAYXUAT));
-- Y6.6---
SELECT HH.MAHH , HH.TENHH, LH.MALOAI,SUM(CT.SOLUONG) AS "SOLUONG" FROM  LOAIHANG LH INNER JOIN HANGHOA HH ON HH.LOAI = LH.MALOAI
INNER JOIN ctphieuxuat CT ON HH.MAHH = CT.MAHH INNER JOIN phieuxuat SP ON CT.SOPHIEU = SP.SOPHIEU and YEAR(SP.NGAYXUAT) =2021 AND MONTH(SP.NGAYXUAT) = 10 
group by(CT.MAHH) ORDER BY
SUM(CT.SOLUONG) desc LIMIT 5 ;-- (SELECT COUNT(CT.MAHH) FROM HANGHOA HH INNER JOIN ctphieuxuat CT ON HH.MAHH = CT.MAHH 
-- INNER JOIN phieuxuat SP ON CT.SOPHIEU = SP.SOPHIEU group by(CT.MAHH) ) ;
-- Y6.7---
SELECT CH.MACH,PX.SOPHIEU,COUNT(PX.SOPHIEU) as "sophieu",CT.SOLUONG*HH.DONGIA AS"TIỀN THANH TOÁN"  FROM CUAHANG CH  ,PHIEUXUAT PX,HANGHOA HH,CTSOPHIEU CT 
WHERE CH.MACH = PX.MACH  AND CH.TENCH = "Vân Thanh Fashion – Chi nhánh Quận 5"
 GROUP BY PX.MACH 

-- SELECT CH.TENCH, COUNT(PX.SOPHIEU) as" SỐ LẦN NHẬP HÀNG", " 
-- FROM CUAHANG CH INNER JOIN PHIEUXUAT PX ON CH.MACH = PX.MACH  AND CH.TENCH = "Vân Thanh Fashion – Chi nhánh Quận 5"
--  INNER JOIN CTPHIEUXUAT CT 
-- ON PX.SOPHIEU = CT.SOPHIEU INNER JOIN HANGHOA HH ON CT.MAHH = HH.MAHH GROUP BY PX.MACH;
-- Y6.8---
SELECT PX.NGAYXUAT, COUNT(DAY(PX.NGAYXUAT)) AS"SỐ LẦN XUẤT TRONG NGÀY" ,CT.SOLUONG*HH.DONGIA AS"TIỀN THANH TOÁN" 
FROM PHIEUXUAT PX INNER JOIN CTPHIEUXUAT CT ON PX.SOPHIEU = CT.SOPHIEU INNER JOIN HANGHOA HH ON CT.MAHH = HH.MAHH GROUP BY DAY(PX.NGAYXUAT);
-- Y6.9---
-- UPDATE PHIEUXUAT 
-- SET NGAYXUAT="2021-10-04" WHERE NGAYXUAT in (SELECT * FROM (SELECT NGAYXUAT FROM PHIEUXUAT WHERE NGAYXUAT  = null) AS NGAY);
UPDATE PHIEUXUAT 
SET NGAYXUAT = "2022-04-10" WHERE NGAYXUAT IS NULL;
-- Y6.10---
UPDATE HANGHOA 
SET DONGIA = DONGIA*0.9 WHERE LOAI in (SELECT * FROM ( SELECT LOAIHANG.MALOAI FROM LOAIHANG 
INNER JOIN HANGHOA ON LOAIHANG.MALOAI = HANGHOA.LOAI AND LOAIHANG.TENLOAI ="Đồng phục học sinh") as ma );
-- Y6.11---
DELETE from CUAHANG WHERE MACH NOT IN ( SELECT * FROM ( SELECT PX.MACH from PHIEUXUAT PX INNER JOIN CUAHANG CH ON PX.MACH = CH.MACH)AS MA);
-- Y6.12---
SELECT HH.MAHH,HH.TENHH,SUM(CT.SOLUONG) AS "THẤP NHẤT" FROM HANGHOA HH INNER JOIN CTPHIEUXUAT CT ON CT.MAHH = HH.MAHH group by CT.MAHH HAVING sum(CT.SOLUONG) <= 
(SELECT SUM(CT.SOLUONG) FROM HANGHOA HH 
INNER JOIN CTPHIEUXUAT CT ON CT.MAHH = HH.MAHH group by CT.MAHH limit 1) order by SUM(CT.SOLUONG) asc  ;
-- Y6.13--- 
SELECT HH.MAHH, HH.TENHH , LH.TENLOAI FROM HANGHOA HH INNER JOIN LOAIHANG LH ON HH.LOAI = LH.MALOAI AND HH.MAHH 
NOT IN (select CT.MAHH FROM CTPHIEUXUAT CT INNER JOIN HANGHOA HH ON HH.MAHH = CT.MAHH );