USE QLNHATRO_PS20520THANHHA
--2a
DROP PROC IF EXISTS search_nhatro;
GO
CREATE PROC search_nhatro @QUAN NVARCHAR(20), @DIENTICHMIN NUMERIC, @DIENTICHMAX NUMERIC,@NGAYDANGTU DATE,@NGAYDANGDEN DATE,@GIANHATU MONEY, @GIANHADEN MONEY,@LOAINHA NVARCHAR(50)
AS
	BEGIN
			SELECT  N'Cho thuê phòng tại : ' + DIACHINHA +' '+ N.QUAN as N'Địa chỉ trọ' ,CAST(DIENTICH AS VARCHAR) +' m2' as N'Diện tích', FORMAT(GIANHA,'N','vi-VN')as N'Giá nhà' ,MOTA,CONVERT(VARCHAR,NGAYDANG,105) as N'Ngày đăng' ,( SELECT IIF(GIOITINH LIKE '%Nam%' , 'A.', 'C.')+TENND) as N'Tên người liên hệ' ,DIENTHOAI ,DIACHI FROM NHATRO N INNER JOIN NGUOIDUNG D ON N.MA_NGLH = D.MA_NGD AND  DIENTICH BETWEEN @DIENTICHMIN AND @DIENTICHMAX AND NGAYDANG BETWEEN @NGAYDANGTU AND @NGAYDANGDEN AND GIANHA BETWEEN @GIANHATU AND @GIANHADEN AND N.QUAN LIKE @QUAN INNER JOIN LOAINHA L ON L.MALOAI = N.MALOAI AND L.TENLOAI LIKE @LOAINHA ;
	END

EXEC search_nhatro N'Quận 6', 20, 30, '2022-01-01','2022-07-01',2000000,3500000,N'Phòng trọ khép kín'

--2-c
DROP FUNCTION IF EXISTS danhgia_nhatro_function
GO
CREATE FUNCTION danhgia_nhatro_function (@SL NVARCHAR(10))
RETURNS @TONG TABLE(LIKES INT, DISLIKE INT ) 
AS
BEGIN
	INSERT INTO @TONG VALUES   ((SELECT COUNT(TRANGTHAI) FROM DANHGIA WHERE MANTR = @SL GROUP BY MANTR, TRANGTHAI HAVING TRANGTHAI = 'LIKE') ,(SELECT COUNT(TRANGTHAI) FROM DANHGIA WHERE MANTR = @SL GROUP BY MANTR, TRANGTHAI HAVING TRANGTHAI = 'DISLIKE'));
		RETURN ;
END
select * FROM   dbo.danhgia_nhatro_function('NT0103') 
select * from NGUOIDUNG


--2B
DROP FUNCTION IF EXISTS search_nguoidung_function
go
CREATE FUNCTION  search_nguoidung_function 
(@MA_NGD NVARCHAR( 20), @MANT NVARCHAR(10), @TENND NVARCHAR(30), @GIOITINH NVARCHAR(10), @DIENTHOAI INT, @DIACHI NVARCHAR(50), @QUAN NVARCHAR(20), @EMAIL NVARCHAR(50))
RETURNS NVARCHAR(20)
AS
BEGIN
declare @ma nvarchar(20);
		IF (@MA_NGD in (SELECT MA_NGD FROM NGUOIDUNG)) AND (@MANT in (SELECT MANT FROM NGUOIDUNG)) AND (@TENND in (SELECT TENND FROM NGUOIDUNG)) AND (@GIOITINH in (SELECT GIOITINH FROM NGUOIDUNG)) AND (@DIENTHOAI in (SELECT DIENTHOAI FROM NGUOIDUNG))AND (@DIACHI in (SELECT DIACHI FROM NGUOIDUNG)) AND
		(@QUAN in (SELECT QUAN FROM NGUOIDUNG)) AND (@EMAIL in (SELECT EMAIL FROM NGUOIDUNG)) 
		BEGIN
		set @ma = @MA_NGD
			
		END
		RETURN @ma
END

select dbo.search_nguoidung_function( 'N01LH004',N'NT0101',N'Minh Thi',N'Nữ',979330927,N'Đường số 54A, phường Tân Tạo',N'Quận Bình Tân',N'thi123@gmail.com' )


--2d
DROP VIEW IF EXISTS view_top10_thongtin ;
go
CREATE VIEW view_top10_thongtin 
AS
SELECT top 10  DIENTICH, GIANHA, MOTA, NGAYDANG,TENND, DIACHI, DIENTHOAI, EMAIL FROM NHATRO  N INNER JOIN NGUOIDUNG D ON N.MA_NGLH = D.MA_NGD inner join 
(SELECT N.MANT , COUNT(TRANGTHAI) SL FROM NHATRO  N inner join DANHGIA G ON N.MANT = G.MANTR GROUP
BY N.MANT,TRANGTHAI HAVING TRANGTHAI ='LIKE') A ON N.MANT = A.MANT ORDER BY SL DESC;
select *from view_top10_thongtin;
select * from DANHGIA
SELECT * FROM NGUOIDUNG
select * from NHATRO

--2E
DROP PROC IF EXISTS search_nhatro_proc 
go
CREATE PROC search_nhatro_proc @MANT NVARCHAR(10)
AS
BEGIN
		IF @MANT IN (SELECT MANT FROM NHATRO)
				BEGIN
						SELECT G.MANTR , TENND, TRANGTHAI, ND FROM NGUOIDUNG D INNER JOIN DANHGIA  G ON  D.MA_NGD = g.MA_NGD WHERE G.MANTR = @MANT;
				END
		ELSE
		PRINT N'Không tồn tại mã nhà trọ'
END
EXEC search_nhatro_proc 'NT0102'
SELECT * FROM NGUOIDUNG


--3.1
DROP PROC IF EXISTS DELETE_NHATRO_PROC_DISLIKE
GO
CREATE PROC DELETE_NHATRO_PROC_DISLIKE @SLDISLIKE INT
AS
BEGIN TRY

		DECLARE @VIEW_LIKE_DISLIKE TABLE (MANT NVARCHAR(10));
		INSERT INTO @VIEW_LIKE_DISLIKE SELECT N.MANT   FROM NHATRO N INNER JOIN (SELECT MANT , COUNT(TRANGTHAI) AS SL FROM NHATRO N INNER JOIN DANHGIA G ON N.MANT = G.MANTR GROUP BY MANT, TRANGTHAI HAVING  TRANGTHAI = 'DISLIKE') A ON N.MANT =A.MANT AND SL >= @SLDISLIKE
		BEGIN TRAN 
		DELETE FROM DANHGIA WHERE MANTR in(select MANT from @VIEW_LIKE_DISLIKE)
		UPDATE  NGUOIDUNG SET MANT = 'NT0101' WHERE MANT in(select MANT from @VIEW_LIKE_DISLIKE)		
		delete from NHATRO where MANT in(select MANT from @VIEW_LIKE_DISLIKE)
		PRINT 'Xoá thành công'
		commit tran 
	END TRY
		BEGIN CATCH
	ROLLBACK TRAN
	 PRINT N'THẤT bại'
	END CATCH
		exec DELETE_NHATRO_PROC_DISLIKE 2

		--3.2
		
		DROP PROC IF EXISTS DELETE_NHATRO_PROC_DATE ;
		GO
		CREATE PROC DELETE_NHATRO_PROC_DATE @NGAYDANGTU DATE , @NGAYDANGDEN DATE 
AS
BEGIN TRY
		DECLARE @VIEW_DELETE_DATE TABLE (MANT NVARCHAR(10));
		INSERT INTO @VIEW_DELETE_DATE SELECT MANT FROM NHATRO WHERE NGAYDANG BETWEEN @NGAYDANGTU AND @NGAYDANGDEN
		BEGIN TRAN 
		DELETE FROM DANHGIA WHERE MANTR in(select MANT from @VIEW_DELETE_DATE)
		UPDATE  NGUOIDUNG SET MANT = 'NT0101' WHERE MANT in(select MANT from @VIEW_DELETE_DATE)		
		delete from NHATRO where MANT in(select MANT from @VIEW_DELETE_DATE)
		PRINT N'Xoá thành công'
		commit tran 
	END TRY
		BEGIN CATCH
	ROLLBACK TRAN
	 PRINT N'Xoá thất bại'
	END CATCH

EXEC DELETE_NHATRO_PROC_DATE  '2022-05-05','2022-06-22'

