SELECT * FROM  PHANCONG;
SELECT * FROM  CONGVIEC;
SELECT * FROM  DEAN;
BEGIN
DECLARE @BANG TABLE (TENDA NVARCHAR(50), THOIGIAN INT ) ;
INSERT INTO @BANG SELECT DEAN.TENDA, SUM(THOIGIAN) FROM PHANCONG INNER JOIN CONGVIEC ON PHANCONG.MADAN = CONGVIEC.MADA INNER JOIN DEAN ON CONGVIEC.MADA = DEAN.MADA   GROUP BY DEAN.TENDA ;
SELECT * FROM @BANG;
END;
 DECLARE @TEN NVARCHAR(10);
 SET @TEN = 'Khanh';
-- select LOWER(@TEN),REPLACE(@TEN,(CHARINDEX('h',@TEN),UPPER(substring(@TEN,(CHARINDEX('h',@TEN)),1)));
  select STUFF(LOWER(@TEN),2,1, UPPER(substring(@TEN,2,1)));