use quanlydulich;
SELECT D.MADDL, D.TENDDL, TT.TENTTP FROM DIEMDL D INNER JOIN TINHTP TT ON D.MATTP = TT.MATTP AND TT.TENTTP = "Lâm Đồng";
SELECT T.MATOUR , T.TENTOUR FROM TOUR T INNER JOIN CHITIET CT ON T.MATOUR = CT.MATOUR GROUP BY CT.MATOUR HAVING COUNT(CT.MATOUR) > (SELECT COUNT(CT.MATOUR) FROM CHITIET CT GROUP BY CT.MATOUR LIMIT 1);
SELECT  T.MATOUR , T.TENTOUR FROM TOUR T WHERE T.PTDI="Máy bay" and T.PTVE ="Máy bay" and T.GIALE < (select T.GIALE FROM TOUR T WHERE T.PTDI="Máy bay" and T.PTVE ="Máy bay"LIMIT 1);