use quanlylichday;
-- SELECT GV.MAGV, GV.HOTEN , L.TENLOP, MH.TENMH, LD.PHONG, LD.NGAYDAY, LD.TUTIET, LD.DENTIET, LD.BAIDAY, LD.GHICHU FROM LOP L INNER JOIN KHOA K ON K.MAKHOA = L.MAKH INNER JOIN GIAOVIEN GV  ON GV.MAKHOA = K.MAKHOA AND GV.MAKHOA = "CNTT"  INNER JOIN LICHDAY LD ON GV.MAGV = LD.MAGIAOVIEN  INNER JOIN MONHOC MH ON LD.MAMH = MH.MAMH AND LD.NGAYDAY = "2002/09/23" AND LD.PHONG IN ( SELECT P.PHONG FROM LICHDAY LD INNER JOIN PHONGHOC P ON LD.PHONG = P.PHONG);
-- SELECT GV.MAGV, GV.HOTEN , L.TENLOP, MH.TENMH, LD.PHONG, LD.NGAYDAY, LD.TUTIET, LD.DENTIET, LD.BAIDAY, LD.GHICHU FROM MONHOC MH INNER JOIN LICHDAY LD  ON LD.MAMH = MH.MAMH  AND LD.NGAYDAY = "2002/09/23" INNER JOIN  LOP L ON LD.MALOP = L.MALOP INNER JOIN KHOA K ON L.MAKH = K.MAKHOA INNER JOIN  GIAOVIEN GV ON GV.MAKHOA = K.MAKHOA AND GV.MAKHOA = "CNTT";
SELECT TENKHOA , COUNT(MAGV) AS "SOLUONGGIAOVIEN" FROM KHOA K INNER JOIN GIAOVIEN GV ON K.MAKHOA = GV.MAKHOA GROUP BY (GV.MAKHOA) ;
select GV.MAGV, GV.HOTEN, MH.TENMH, P.PHONG, LD.NGAYDAY,LD.TUTIET,LD.DENTIET,LD.BAIDAY,LD.GHICHU
FROM GIAOVIEN GV INNER JOIN MONHOC MH 
ON GV.MAGV = MH.MAGV
INNER JOIN KHOA K 
ON K.MAKHOA = GV.MAKHOA
AND GV.MAKHOA ="CNTT" 
INNER JOIN LOP L 
ON L.MAKH = K.MAKHOA
INNER JOIN LICHDAY LD 
ON LD.MALOP = L.MALOP
AND LD.MAGIAOVIEN = GV.MAGV 
AND LD.MAMH = MH.MAMH
INNER JOIN PHONGHOC P
ON P.PHONG = LD.PHONG 
AND LD.NGAYDAY = "2002-09-23";
-- cho phép liên kết không theo trình tự các bảng trong inner join



