use quanlyviecthitotnghiep;
-- 2-a---
SELECT TS.SOBD , TS.TENTS , T.TENTR FROM THISINH TS INNER JOIN TRUONG T ON T.MATR = TS.MATRUONG AND T.TENTR LIKE "%Nguyễn Thị Minh Khai";
-- 2-b---
SELECT  TS.SOBD , TS.TENTS , KQ.DIEMTHI  FROM KETQUA KQ INNER JOIN  THISINH TS ON TS.SOBD = KQ.SOBD INNER JOIN TRUONG T ON T.MATR = TS.MATRUONG AND TS.MATRUONG= "NCT" AND MAMT = "V" ORDER BY KQ.DIEMTHI DESC;
-- 2-c---
SELECT T.MATR , T.TENTR , PT.SOPT  , count(TS.SOPT) AS "SỐ LƯỢNG SINH VIÊN" , DCPT FROM TRUONG T INNER JOIN THISINH TS ON T.MATR = TS.MATRUONG INNER JOIN PHONGTHI PT ON TS.SOPT = PT.SOPT GROUP BY (TS.SOPT) ORDER BY SOPT ASC; 
-- 2-d---
SELECT TS.SOBD , TS.TENTS , TS.NGAYSINH , TS.PHAI , TS.MATRUONG ,TR.TENTR , TS.SOPT, MT.TENMT , KQ.DIEMTHI FROM TRUONG TR INNER JOIN THISINH TS ON TR.MATR = TS.MATRUONG INNER JOIN KETQUA KQ ON TS.SOBD = KQ.SOBD AND KQ.DIEMTHI < 5 INNER JOIN MONTHI MT ON KQ.MAMT = MT.MAMT;
-- 2-e---
SELECT MT.MAMT , MT.TENMT FROM MONTHI MT WHERE MT.NGAYTHI = "2010/05/21";
-- SELECT KQ.SOBD, TENTS, DIEMTHI
-- FROM MONTHI MT INNER JOIN KETQUA KQ ON MT.MAMT = KQ.MAMT
-- 	 INNER JOIN THISINH TS ON TS.SOBD = KQ.SOBD
--      INNER JOIN TRUONG T ON T.MATR = TS.MATR
--      AND DIEMTHI IN (SELECT DIEMTHI FROM KETQUA WHERE MAMT LIKE 'V')
--      AND KQ.SOBD IN (SELECT SOBD FROM THISINH WHERE MATR LIKE 'NCT')
-- ORDER BY DIEMTHI DESC;