
use quanlibanhang;
-- CAU2.A--
update KHACH_HANG 
SET DIEN_THOAI = "16267788989" where ma_KH ="KH002";
-- CAU2.B--
UPDATE SAN_PHAM 
SET SO_LUONG = SO_LUONG + 200 WHERE MA_SP ="3";
-- CAU2.C--
UPDATE SAN_PHAM 
SET DON_GIA = DON_GIA - DON_GIA*0.05;
-- CAU2.D--

UPDATE SAN_PHAM
SET SOlUONG = SO_LUONG +100;
SELECT MA_SP FROM HOA_DON HD
INNER JOIN HOA_DON_CHI_TIET HDCT ON HDCT.MA_HD = HD.MA_HD
WHERE MONTH(NGAY_MUAHANG) = 12 AND YEAR(NGAY_MUAHANG) = 2016
GROUP BY MA_SP
ORDER BY SUM(SO_LUONG) DESC
LIMIT 1;
-- CAU2.E--
update san_pham 
set DON_GIA = DON_GIA*0.9 WHERE MA_SP IN ( SELECT * FROM ( select MA_SP FROM HOA_DON_CHI_TIET HDCT INNER JOIN HOA_DON HD ON HDCT.MA_HD = HD.MA_HD
WHERE HD.NGAY_MUAHANG between "2016-01-01" AND "2016-12-31" group by MA_SP order by SUM(SO_LUONG) ASC LIMIT 2) AS ABC);
-- CAU2.F--
UPDATE HOA_DON
SET TRANG_THAI ="Đã thanh toán" where MA_HD ="120956";
-- CAU2.G--
delete from HOA_DON_CHI_TIET WHERE MA_HDCT = ( SELECT MAHDCT FROM (SELECT distinct HDCT.MA_HDCT AS MAHDCT FROM HOA_DON HD , HOA_DON_CHI_TIET HDCT 
WHERE HD.MA_HD = HDCT.MA_HD 
AND HD.MA_HD = "120956" AND HD.TRANG_THAI ="Chưa thanh toán" and HDCT.MA_SP = 2)AS C);
-- CAU2.H--
DELETE FROM KHACH_HANG WHERE Ma_KH NOT IN (SELECT makh from ( select DISTINCT  KH.ma_KH as makh 
FROM KHACH_HANG KH INNER JOIN HOA_DON HD ON KH.MA_KH = HD.MA_KHACHHANG AND HD.NGAY_MUAHANG >="2016-01-01") as ma) ;