use quanlybanhang;
-- PS20520_Nguyen Thanh Ha_lab6bai2---
-- bai2lab6.a--
SELECT * FROM KHACH_HANG KH WHERE NOT KH.MA_KH NOT IN (SELECT MA_KHACHHANG FROM HOA_DON HD
 INNER JOIN  KHACH_HANG KH ON HD.MA_KHACHHANG = KH.ma_KH AND HD.NGAY_MUAHANG > "2016-01-01");
-- bai2lab6.b--
-- Hiển thị mã sản phẩm, tên sản phẩm có lượt mua nhiều nhất trong tháng 12/2016---
SELECT SP.MA_SP , SP.TEN_SP , COUNT(HDCT.MA_SP) AS "sỐ LƯỢT MUA" FROM SAN_PHAM SP , HOA_DON HD, HOA_DON_CHI_TIET HDCT WHERE 
SP.MA_SP = HDCT.MA_SP AND HD.MA_HD = HDCT.MA_HD AND HD.NGAY_MUAHANG between "2016-12-01" AND "2016-12-31" 
group by HDCT.Ma_SP HAVING  COUNT(HDCT.MA_SP) >= ALL(SELECT  COUNT(HDCT.MA_SP) FROM SAN_PHAM SP , HOA_DON HD, HOA_DON_CHI_TIET HDCT WHERE 
SP.MA_SP = HDCT.MA_SP AND HD.MA_HD = HDCT.MA_HD AND HD.NGAY_MUAHANG between "2016-12-01" AND "2016-12-31" 
group by HDCT.MA_SP);
-- bai2lab6.c--
-- Hiển thị top 5 khách hàng có tổng số tiền mua hàng nhiều nhất trong năm 2016--
SELECT SP.MA_SP , SP.TEN_SP FROM HOA_DON_CHI_TIET HDCT,SAN_PHAM SP , HOA_DON HD WHERE SP.MA_SP = HDCT.MA_SP AND HD.MA_HD = HDCT.MA_HD
GROUP BY SP.MA_SP HAVING COUNT(HDCT.MA_SP) <= ALL(SELECT COUNT(HDCT.MA_SP) FROM HOA_DON_CHI_TIET HDCT,SAN_PHAM SP , HOA_DON HD WHERE SP.MA_SP = HDCT.MA_SP AND HD.MA_HD = HDCT.MA_HD
GROUP BY SP.MA_SP );
SELECT SP.MA_SP , SP.TEN_SP FROM HOA_DON_CHI_TIET HDCT,SAN_PHAM SP , HOA_DON HD WHERE SP.MA_SP = HDCT.MA_SP AND HD.MA_HD = HDCT.MA_HD
GROUP BY SP.MA_SP;
SELECT KH.MA_KH , CONCAT(KH.HO_VA_TENlOT,'',KH.TEN) AS "HỌ VÀ TÊN " ,HD.MA_HD, HD.NGAY_MUAHANG, SUM(HDCT.SO_LUONG*SP.DON_GIA) AS "THÀNH TIỀN"
FROM KHACH_HANG KH , HOA_DON HD, HOA_DON_CHI_TIET HDCT , SAN_PHAM SP
WHERE  SP.MA_SP = HDCT.MA_SP AND HD.MA_HD = HDCT.MA_HD AND HD.MA_KHACHHANG = KH.MA_KH AND HD.NGAY_MUAHANG BETWEEN "2016-01-01" AND "2016-12-31"
group by HD.MA_KHACHHANG limit 5;
-- SELECT SP.MA_SP , SP.TEN_SP , COUNT(HDCT.MA_SP) AS "sỐ LƯỢT MUA" FROM SAN_PHAM SP , HOA_DON HD, HOA_DON_CHI_TIET HDCT WHERE 
-- SP.MA_SP = HDCT.MA_SP AND HD.MA_HD = HDCT.MA_HD AND HD.NGAY_MUAHANG between "2016-12-01" AND "2016-12-31" 
-- group by HDCT.Ma_SP HAVING  COUNT(HDCT.MA_SP) >= ALL(SELECT  COUNT(HDCT.MA_SP) FROM SAN_PHAM SP , HOA_DON HD, HOA_DON_CHI_TIET HDCT WHERE 
-- SP.MA_SP = HDCT.MA_SP AND HD.MA_HD = HDCT.MA_HD AND HD.NGAY_MUAHANG between "2016-12-01" AND "2016-12-31" 
-- group by HDCT.MA_SP);
SELECT HD.MA_HD, HD.NGAY_MUAHANG,  HDCT.SO_LUONG*SP.DON_GIA AS "Tổng tiền" FROM HOA_DON HD INNER JOIN HOA_DON_CHI_TIET HDCT ON HD.Ma_HD = HDCT.MA_HD 
INNER JOIN SAN_PHAM SP ON HDCT.Ma_SP = SP.ma_SP AND HDCT.SO_LUONG*SP.DON_GIA >=500000 order by HDCT.SO_LUONG*SP.DON_GIA DESC;
SELECT * FROM KHACH_HANG KH WHERE KH.DIA_CHI like "%Đà Nẵng%" and KH.MA_KH = (SELECT HD.MA_KHACHHANG FROM HOA_DON HD, SAN_PHAM SP , HOA_DON_CHI_TIET HDCT 
WHERE SP.MA_SP = HDCT.MA_SP AND HD.MA_HD = HDCT.MA_HD AND HD.MA_KHACHHANG = KH.MA_KH AND SP.TEN_SP = "Iphone 7 32 GB" and HD.NGAY_MUAHANG BETWEEN "2016-12-01" AND "2016-12-31" ) ;