CREATE database quanLyBanHang;
USE quanLyBanHang;
CREATE TABLE KHACH_HANG(
ma_KH VARCHAR(5) PRIMARY KEY NOT NULL,
HO_VA_TENLOT VARCHAR(50) NOT NULL, 
TEN VARCHAR(50) NOT NULL,
DIA_CHI VARCHAR(255) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
DIEN_THOAI VARCHAR(13) NOT NULL
);
CREATE TABLE San_Pham(
ma_SP INT PRIMARY KEY NOT NULL ,
MO_TA VARCHAR(255) NOT NULL,
SO_LUONG INT NOT NULL,
DON_GIA numeric NOT NULL,
TEN_SP VARCHAR(30) NOT NULL
);
CREATE TABLE HOA_DON(
Ma_HD INT PRIMARY KEY NOT NULL,
NGAY_MUAHANG DATE NOT NULL,
MA_KHACHHANG VARCHAR(5) NOT null,
TRANG_THAI VARCHAR(30) NOT NULL
);
CREATE TABLE HOA_DON_CHI_TIET(
MA_HD INT NOT NULL,
Ma_SP INT NOT NULL,
SO_LUONG INT NOT NULL,
Ma_HDCT INT PRIMARY KEY NOT NULL
);hoa_don