CREATE database QUANLYNHANVIEN;
USE QUANLYNHANVIEN;
create TABLE NHAN_VIEN(
ID_NHANVIEN INT primary KEY,
HO_NV VARCHAR(45) NOT NULL,
TEN_NV VARCHAR(45) NOT NULL ,
NAMSINH DATE NOT NULL,
DIA_CHI VARCHAR(45) NOT NULL,
GIOI_TINH VARCHAR(45) NOT NULL,
LUONG INT NOT NULL,
PHG INT NOT NULL
);
CREATE TABLE PHONG_BAN (
MA_PB INT PRIMARY KEY NOT NULL,
TEN_PB varchar(45) not null,
ma_truongphong int not null
);
create TABLE QUANLY_DUAN ( 
MA_DUAM INT PRIMARY KEY NOT NULL,
MA_NHANVIEN INT NOT NULL,
NGAY_THAMGIA DATE NOT NULL,
NGAY_KETTHUC DATE NOT NULL,
SO_GIO INT NOT NULL,
VAI_TRO VARCHAR(45) NOT NULL
);
CREATE TABLE DU_AN (
MA_DUAN INT PRIMARY KEY NOT NULL,
TEN_DUAN VARCHAR(45) NOT NULL,
NGAY_BATDAU DATE NOT NULL,
NAY_KETTHUC DATE NOT NULL
);
ALTER TABLE `quanlynhanvien`.`nhan_vien` 
ADD CONSTRAINT `nhan_vien`
  FOREIGN KEY (`PHG`)
  REFERENCES `quanlynhanvien`.`phong_ban` (`MA_PB`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  ALTER TABLE `quanlynhanvien`.`quanly_duan` 
ADD CONSTRAINT `quanly_phongban`
  FOREIGN KEY (`MA_NHANVIEN`)
  REFERENCES `quanlynhanvien`.`nhan_vien` (`ID_NHANVIEN`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  ALTER TABLE `quanlynhanvien`.`quanly_duan` 
ADD CONSTRAINT `du_an`
  FOREIGN KEY (`MA_DUAM`)
  REFERENCES `quanlynhanvien`.`quanly_duan` (`MA_DUAM`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
