use testdl;
SELECT * FROM DKKHOA ORDER BY TENKHOA DESC;
SELECT * FROM DKKHOA WHERE TENKHOA LIKE "%Ngữ%" or TENKHOA LIKE '%học%';
SELECT SV.MASV , SV.HOTEN, SV.NGAYSINH, K.TENKHOA FROM SINHVIEN SV INNER JOIN DKKHOA K ON SV.MAKH = K.MAKHOA AND K.MAKHOA = 'DPH';
SELECT K.MAKHOA , K.TENKHOA FROM SINHVIEN SV INNER JOIN DKKHOA K ON SV.MAKH = K.MAKHOA GROUP BY SV.MAKH HAVING COUNT(SV.MAKH)<2;
SELECT  SV.MASV, SV.HOTEN , 2022 - year(SV.NGAYSINH) AS 'TUOI' FROM SINHVIEN SV INNER JOIN DKKHOA K ON K.MAKHOA = SV.MAKH  AND 2022 - year(SV.NGAYSINH) < (SELECT avg(2022 - year(SV.NGAYSINH)) FROM SINHVIEN SV INNER JOIN DKKHOA K ON K.MAKHOA = SV.MAKH);
UPDATE  SINHVIEN , DKKHOA
SET DKKHOA.TENKHOA = "Ngôn ngữ học" where SINHVIEN.MAKH = DKKHOA.MAKHOA AND HOTEN ="Lê Thu Thảo";