/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asm1;

import static java.lang.Thread.sleep;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/**
 *
 * @author Vie
 */
public class Loading extends javax.swing.JFrame {

    progressBar proBar;
    /**
     * Creates new form Loading
     */
    public Loading() {
        initComponents();
        setLocationRelativeTo(null);
        proBar = new progressBar(jProgressBar1);
        proBar.start();
    }
   
        class progressBar extends Thread {

        JProgressBar bar;

        progressBar(JProgressBar bar) {
            this.bar = bar;
        }

        @Override
        public void run() {
            bar.setMinimum(0);
            bar.setMaximum(100);
            bar.setValue(0);
            for (int i = 0; i <= 100; i += 5) {
                bar.setValue(i);
                try {
                    sleep(200);
                } catch (InterruptedException ex) {
                }
                loadingValue1.setText(i + "%");
                if (i == 20) {
                    loadingLabel.setText("Đang Kết Nối Data....");
                }
                
                if (i == 65) {
                    loadingLabel.setText("Đang Đồng Bộ Dữ liệu....");
                }
                
                if (i == 100) {
                    JOptionPane.showMessageDialog(null, "Đăng Nhập Thành Công");
                    dispose();
                }
            }
        }

    }
    
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        loadingLabel = new javax.swing.JLabel();
        greetingLabel = new javax.swing.JLabel();
        loadingValue1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asm1/img/icons8_workspace_80px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 21, -1, 63));

        jProgressBar1.setForeground(new java.awt.Color(69, 171, 124));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 268, 677, 40));

        loadingLabel.setBackground(new java.awt.Color(69, 171, 124));
        loadingLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loadingLabel.setForeground(new java.awt.Color(125, 136, 252));
        loadingLabel.setText("LoaDing");
        jPanel1.add(loadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 240, 27));
        jPanel1.add(greetingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 115, 196, 54));

        loadingValue1.setBackground(new java.awt.Color(69, 171, 124));
        loadingValue1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loadingValue1.setForeground(new java.awt.Color(125, 136, 252));
        loadingValue1.setText("0%");
        jPanel1.add(loadingValue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 229, 74, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel greetingLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel loadingLabel;
    private javax.swing.JLabel loadingValue1;
    // End of variables declaration//GEN-END:variables


}
