/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bAI1lAB4;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Bai1Lab4 extends javax.swing.JFrame {

    /**
     * Creates new form Bai1Lab4
     */
    public Bai1Lab4() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnnew = new javax.swing.JButton();
        btnusser = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcontent = new javax.swing.JTextArea();
        txtps20520 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menunew = new javax.swing.JMenuItem();
        menuopen = new javax.swing.JMenuItem();
        menusave = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menured = new javax.swing.JMenuItem();
        menugreen = new javax.swing.JMenuItem();
        menublue = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menutxtcolor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuabout = new javax.swing.JMenuItem();
        menuexit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bAI1lAB4/new-document (1).png"))); // NOI18N
        btnnew.setFocusable(false);
        btnnew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnnew);

        btnusser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bAI1lAB4/user.png"))); // NOI18N
        btnusser.setFocusable(false);
        btnusser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnusser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnusser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusserActionPerformed(evt);
            }
        });
        jToolBar1.add(btnusser);

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bAI1lAB4/exit.png"))); // NOI18N
        btnexit.setFocusable(false);
        btnexit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnexit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnexit);

        txtcontent.setColumns(20);
        txtcontent.setRows(5);
        txtcontent.setText("Cong cha nhu nui thai son\nNghia me nhu nuoc trong nguon chay ra\nMot long tho me kinh châ\nCho long chu hieu moi là dao con\n\nUống nước nhớ nguồn\n..............");
        jScrollPane1.setViewportView(txtcontent);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        );

        txtps20520.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtps20520.setText("PS20520_NGUYỄN THANH HÀ _ IT17326_LAB4");

        jMenu1.setText("File");

        menunew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menunew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bAI1lAB4/new-document (1).png"))); // NOI18N
        menunew.setText("New");
        menunew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunewActionPerformed(evt);
            }
        });
        jMenu1.add(menunew);

        menuopen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuopen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bAI1lAB4/open.png"))); // NOI18N
        menuopen.setText("Open");
        menuopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuopenActionPerformed(evt);
            }
        });
        jMenu1.add(menuopen);

        menusave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menusave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bAI1lAB4/save.png"))); // NOI18N
        menusave.setText("Save");
        menusave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusaveActionPerformed(evt);
            }
        });
        jMenu1.add(menusave);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Color");

        menured.setText("Red");
        menured.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuredActionPerformed(evt);
            }
        });
        jMenu3.add(menured);

        menugreen.setText("Green");
        menugreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menugreenActionPerformed(evt);
            }
        });
        jMenu3.add(menugreen);

        menublue.setText("Blue");
        menublue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menublueActionPerformed(evt);
            }
        });
        jMenu3.add(menublue);
        jMenu3.add(jSeparator2);

        menutxtcolor.setText("Text Color");
        menutxtcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutxtcolorActionPerformed(evt);
            }
        });
        jMenu3.add(menutxtcolor);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("System");

        menuabout.setText("About us");
        menuabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuaboutActionPerformed(evt);
            }
        });
        jMenu4.add(menuabout);

        menuexit.setText("Exit");
        menuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuexitActionPerformed(evt);
            }
        });
        jMenu4.add(menuexit);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtps20520)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtps20520, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuopenActionPerformed
        // TODO add your handling code here:
        JFileChooser file =  new JFileChooser();
        file.showOpenDialog(null);
        int select = JFileChooser.APPROVE_OPTION;
        if(select == JFileChooser.APPROVE_OPTION){ 
            String path = file.getSelectedFile().getAbsolutePath();
             try {
            FileReader fr = new FileReader(file.getSelectedFile());
                 BufferedReader br = new BufferedReader(fr);
                 String line ;
                 while((line = br.readLine()) != null){ 
                     txtcontent.setText( txtcontent.getText()+line+ "\n" );
                    
                 }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Bai1Lab4.class.getName()).log(Level.SEVERE, null, ex);
        }   catch (IOException ex) {
                Logger.getLogger(Bai1Lab4.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
       
        
    }//GEN-LAST:event_menuopenActionPerformed

    private void menunewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menunewActionPerformed
        // TODO add your handling code here:
        txtcontent.setText("");
    }//GEN-LAST:event_menunewActionPerformed

    private void menusaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusaveActionPerformed
        // TODO add your handling code here:
        try {
             JFileChooser file = new JFileChooser();
        file.showSaveDialog(null);
         int select = JFileChooser.APPROVE_OPTION;
        if(select == JFileChooser.APPROVE_OPTION ){ 
            try {
                FileWriter fw = new FileWriter(file.getSelectedFile());
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(txtcontent.getText());
                bw.flush();
                bw.close();
            } catch (IOException ex) {
                Logger.getLogger(Bai1Lab4.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        } catch (Exception e) {
        }
      
    }//GEN-LAST:event_menusaveActionPerformed

    private void menuredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuredActionPerformed
        // TODO add your handling code here:
        txtps20520.setBackground(Color.red);
    }//GEN-LAST:event_menuredActionPerformed

    private void menugreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menugreenActionPerformed
        // TODO add your handling code here:
        txtps20520.setBackground(Color.GREEN);
    }//GEN-LAST:event_menugreenActionPerformed

    private void menublueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menublueActionPerformed
        // TODO add your handling code here:
        txtps20520.setBackground(Color.BLUE);
    }//GEN-LAST:event_menublueActionPerformed

    private void menutxtcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutxtcolorActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null,"Chọn màu chữ", Color.BLACK);
        txtps20520.setForeground(c);
    }//GEN-LAST:event_menutxtcolorActionPerformed

    private void menuaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuaboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Name detail : Notepad fake \n Author : PS20520- Thanh Hà \n Last update : 23-07-2022 \n Education : Poly");
    }//GEN-LAST:event_menuaboutActionPerformed

    private void menuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuexitActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
        txtcontent.setText("");
    }//GEN-LAST:event_btnnewActionPerformed

    private void btnusserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusserActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Vui lòng đăng nhập");
    }//GEN-LAST:event_btnusserActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai1Lab4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai1Lab4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai1Lab4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai1Lab4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai1Lab4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnusser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuabout;
    private javax.swing.JMenuItem menublue;
    private javax.swing.JMenuItem menuexit;
    private javax.swing.JMenuItem menugreen;
    private javax.swing.JMenuItem menunew;
    private javax.swing.JMenuItem menuopen;
    private javax.swing.JMenuItem menured;
    private javax.swing.JMenuItem menusave;
    private javax.swing.JMenuItem menutxtcolor;
    private javax.swing.JTextArea txtcontent;
    private javax.swing.JTextField txtps20520;
    // End of variables declaration//GEN-END:variables
}
